using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Bombs : MonoBehaviour
{
    //発生させるパーティクルを設定
    public GameObject particle;

    void Start()
    {

    }
    void Update()
    {
        //キーボードのBキーが押されたら
        if (Input.GetKeyDown(KeyCode.B))
        {
            //タグが同じオブジェクトをすべて取得する
            GameObject[] enemyBulletObjects =
                GameObject.FindGameObjectsWithTag("EnemyBullet");

            //上で取得したすべてのオブジェクトを消滅させる
            for (int i = 0; i < enemyBulletObjects.Length; i++)
            {
                Destroy(enemyBulletObjects[i].gameObject);
            }
            //パーティクルを持ったオブジェクトを生成する
            Instantiate(particle, Vector3.zero, Quaternion.identity);
        }
    }
};